M48
; DRILL file {KiCad 7.0.9} date Saturday, February 03, 2024 at 09:53:39 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-03T21:53:39-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.8348Y-3.272
X1.8348Y-3.4996
T2
X1.7323Y-3.8976
X3.6772Y-2.8031
T0
M30
